//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// (Hand-written here to keep this example dependency-free of the
// controller-gen binary, but shaped exactly as `controller-gen
// object:headerFile="hack/boilerplate.go.txt" paths="./..."` would emit it.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentClaim) DeepCopyInto(out *EnvironmentClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EnvironmentClaim.
func (in *EnvironmentClaim) DeepCopy() *EnvironmentClaim {
	if in == nil {
		return nil
	}
	out := new(EnvironmentClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentClaimList) DeepCopyInto(out *EnvironmentClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]EnvironmentClaim, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EnvironmentClaimList.
func (in *EnvironmentClaimList) DeepCopy() *EnvironmentClaimList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentClaimSpec) DeepCopyInto(out *EnvironmentClaimSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EnvironmentClaimSpec.
func (in *EnvironmentClaimSpec) DeepCopy() *EnvironmentClaimSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentClaimStatus) DeepCopyInto(out *EnvironmentClaimStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EnvironmentClaimStatus.
func (in *EnvironmentClaimStatus) DeepCopy() *EnvironmentClaimStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentClaimStatus)
	in.DeepCopyInto(out)
	return out
}
